Adding the ability to set provenance hash
coinbase/nft-dapp-starter-kit pull request #28
Opened 2022-07-13 00:06 UTC by Shiva-Tzu

The provenance hash is an important feature for establishing trust between customer and seller if a reveal is occurring. Noticed it was not in the contract so decided to add the functionality in both contract and package.json commands.

2022-07-21 12:43 UTC, jeongmincho commented
nice!!! thanks:) i'll review this by EOW

2022-08-03 08:02 UTC, jeongmincho requested changes
hey @Shiva-Tzu! sorry for the delay. thanks again for adding this! provenance hashes are important for sure. added a few stylistic suggestions but overall looks great. let's get you merged in asap.

2022-08-03 08:02 UTC, jeongmincho commented on smart-contracts/package.json
> +     "setProvenanceHash": "npx hardhat run scripts/setProvenanceHash.js"
```suggestion
    "setProvenanceHash": "npx hardhat run scripts/setProvenanceHash.js",
```

2022-08-03 08:02 UTC, jeongmincho commented on smart-contracts/scripts/setProvenanceHash.js
> +    console.log("BASE_URI is required. Please add it to your environment.");
```suggestion
    console.log("PROVENANCE_HASH is required. Please add it to your environment.");
```

2022-08-03 08:02 UTC, jeongmincho commented on smart-contracts/scripts/setProvenanceHash.js
> +  console.log("TechnoFeudal attached to:", nft.address);
```suggestion
  const MyNFT = await hre.ethers.getContractFactory("MyNFT");
  const nft = await MyNFT.attach(
    process.env.CONTRACT_ADDRESS // The deployed contract address
  );
  console.log("MyNFT attached to:", nft.address);
```

2022-08-03 20:38 UTC, Shiva-Tzu commented
Great! Glad I could assist!

2022-08-14 22:01 UTC, merged